// Central data + configuration for the EXITios operating shell.
// All sample records are explicitly illustrative — never presented as verified production data.

export const WORKSPACE = {
  org: "EXITios Demo Organization",
  name: "Growth Workspace",
  type: "Growth",
  permission: "Owner access",
};

export const DECISION_STATES = [
  "Draft",
  "Needs evidence",
  "Ready for review",
  "Approved",
  "In execution",
  "Revisit",
  "Closed",
];

export const EVIDENCE_STATES = [
  "Not started",
  "Owner-reported",
  "Uploaded",
  "Needs review",
  "Reviewed",
  "Reconciled",
  "Verified in workspace",
];

// Illustrative sample decisions. Clearly labeled in the UI.
export const SAMPLE_DECISIONS = [
  {
    id: "d-001",
    title: "Prioritize retention or acquisition?",
    question: "Should the business prioritize customer retention or new-customer acquisition?",
    area: "Customer economics",
    why: "Acquisition spending should not be increased until customer value and early-life churn are understood.",
    evidence: "Owner-reported information",
    missing: "Monthly customer counts, cancellations and contribution by service type",
    nextAction: "Complete the revenue-quality baseline",
    owner: "Unassigned",
    due: "Not set",
    review: "After baseline is established",
    state: "Needs evidence",
    evidenceState: "Owner-reported",
    overdue: false,
  },
  {
    id: "d-002",
    title: "Which service line should we grow?",
    question: "Which service line should we grow to lift lifetime client value?",
    area: "Service mix",
    why: "Contribution by service line is not yet separated, so growth investment is untargeted.",
    evidence: "Owner-reported information",
    missing: "Contribution by service line",
    nextAction: "Map service-line contribution",
    owner: "You",
    due: "Fri Sep 26",
    review: "Next Friday",
    state: "Needs evidence",
    evidenceState: "Owner-reported",
    overdue: false,
  },
  {
    id: "d-003",
    title: "Increase pricing on the premium tier?",
    question: "Should we increase pricing on the premium service tier this quarter?",
    area: "Pricing",
    why: "Price elasticity for the premium tier is not yet tested against recent win/loss data.",
    evidence: "Uploaded — pricing sheet",
    missing: "Win/loss reasons by tier",
    nextAction: "Review recent lost-deal reasons",
    owner: "You",
    due: "Today",
    review: "This week",
    state: "Ready for review",
    evidenceState: "Needs review",
    overdue: true,
  },
  {
    id: "d-004",
    title: "Add a second service route?",
    question: "Should we open a second service route in the adjacent territory?",
    area: "Capacity",
    why: "Route density and unmet demand are not yet measured for the adjacent territory.",
    evidence: "None",
    missing: "Demand by zip code, current route utilization",
    nextAction: "Request route-density report",
    owner: "Unassigned",
    due: "Not set",
    review: "Not set",
    state: "Draft",
    evidenceState: "Not started",
    overdue: false,
  },
  {
    id: "d-005",
    title: "Renegotiate the supplier contract?",
    question: "Should we renegotiate the primary supplier contract before renewal?",
    area: "Margin",
    why: "Input costs have moved; contribution may improve with revised terms.",
    evidence: "Uploaded — current contract",
    missing: "Competitor pricing benchmarks",
    nextAction: "Collect benchmark quotes",
    owner: "You",
    due: "Mon Sep 29",
    review: "Oct 2",
    state: "Approved",
    evidenceState: "Reviewed",
    overdue: false,
  },
  {
    id: "d-006",
    title: "Sunset a low-margin service?",
    question: "Should we sunset the lowest-margin service line?",
    area: "Service mix",
    why: "The line drags blended margin and ties up technician capacity.",
    evidence: "Reviewed — contribution report",
    missing: "None",
    nextAction: "Closed — transition scheduled",
    owner: "You",
    due: "Completed",
    review: "Completed",
    state: "Closed",
    evidenceState: "Reviewed",
    overdue: false,
  },
];

export const VALUE_LEVERS = [
  {
    name: "Customer retention",
    current: "Not measured",
    evidence: "Not started",
    known: "Customers are tracked by name",
    unknown: "Cohort retention and early-life churn",
    linked: "d-001",
    next: "Complete the retention baseline",
  },
  {
    name: "Revenue per customer",
    current: "Unknown",
    evidence: "Owner-reported",
    known: "Total revenue",
    unknown: "Revenue per customer and by segment",
    linked: null,
    next: "Add revenue-by-customer detail",
  },
  {
    name: "Service mix",
    current: "Blended only",
    evidence: "Owner-reported",
    known: "Service categories offered",
    unknown: "Contribution by service line",
    linked: "d-002",
    next: "Separate contribution by line",
  },
  {
    name: "Pricing",
    current: "List prices only",
    evidence: "Needs review",
    known: "Current rate card",
    unknown: "Realized price and discounting",
    linked: "d-003",
    next: "Reconcile realized price",
  },
  {
    name: "Margin",
    current: "Not calculated",
    evidence: "Not started",
    known: "Revenue",
    unknown: "Direct and indirect cost by line",
    linked: "d-005",
    next: "Build a contribution statement",
  },
  {
    name: "Capacity",
    current: "Headcount only",
    evidence: "Owner-reported",
    known: "Team size",
    unknown: "Utilization and route density",
    linked: "d-004",
    next: "Measure utilization",
  },
];

export const EVIDENCE_CATEGORIES = [
  { name: "Business context", state: "Owner-reported", items: 3 },
  { name: "Financial information", state: "Not started", items: 0 },
  { name: "Customer information", state: "Needs review", items: 2 },
  { name: "Operating information", state: "Uploaded", items: 1 },
  { name: "People and ownership", state: "Owner-reported", items: 1 },
  { name: "Documents", state: "Not started", items: 0 },
  { name: "Decision history", state: "Reviewed", items: 4 },
];

export const EVIDENCE_DETAIL = {
  source: "Owner-reported",
  sourceOwner: "Workspace owner",
  period: "Current",
  uploadDate: "Not uploaded",
  reviewState: "Owner-reported",
  permissionScope: "Workspace members",
  version: "1",
  lastChange: "Created on workspace setup",
  linked: "d-001",
};

export const WORKSPACE_PAGES = {
  growth: {
    title: "Growth workspace",
    subheading: "Turn operating information into focused value-creation work.",
    cta: "Create growth initiative",
    ctaTo: "/app/decisions",
    sections: [
      { name: "Growth decisions", why: "The open questions that shape where growth investment goes.", next: "Start a growth decision", to: "/app/decisions" },
      { name: "Customer economics", why: "Understand what each customer and segment contributes.", next: "Add customer economics evidence", to: "/app/evidence" },
      { name: "Retention", why: "Measure cohort retention and early-life churn before scaling acquisition.", next: "Complete retention baseline", to: "/app/evidence" },
      { name: "Revenue quality", why: "Separate recurring, durable revenue from one-off revenue.", next: "Add revenue-quality evidence", to: "/app/evidence" },
      { name: "Margin and capacity", why: "Find where contribution improves without adding fixed cost.", next: "Build a contribution statement", to: "/app/evidence" },
      { name: "Active initiatives", why: "Owned, dated work tied to a decision and evidence.", next: "Create an initiative", to: "/app/decisions" },
      { name: "Review agenda", why: "The cadence that keeps growth work accountable.", next: "Schedule a review", to: "/app/reviews" },
    ],
  },
  "sell-side": {
    title: "Sell-side workspace",
    subheading: "Prepare for a sale before a buyer asks.",
    cta: "Create readiness plan",
    ctaTo: "/app/decisions",
    sections: [
      { name: "Readiness overview", why: "Where the business stands against what a buyer will examine.", next: "Start readiness review", to: "/app/reviews" },
      { name: "Financial clarity", why: "Consistent, defensible financials across periods.", next: "Add financial evidence", to: "/app/evidence" },
      { name: "Customer concentration", why: "Revenue concentration and contract terms a buyer will flag.", next: "Add customer evidence", to: "/app/evidence" },
      { name: "Owner dependence", why: "How the business runs without the owner present.", next: "Document owner roles", to: "/app/evidence" },
      { name: "Management continuity", why: "Key-person risk across the management team.", next: "Add people evidence", to: "/app/evidence" },
      { name: "Documentation", why: "The records a buyer will request in a data room.", next: "Upload documents", to: "/app/evidence" },
      { name: "Buyer questions", why: "The questions a buyer will ask first — answered before asked.", next: "Prepare answers", to: "/app/decisions" },
      { name: "Open readiness actions", why: "Owned work that moves readiness forward.", next: "Create a readiness action", to: "/app/decisions" },
    ],
    maturity: ["Not started", "Information requested", "Submitted", "Reviewed", "Ready for buyer review"],
  },
  acquisition: {
    title: "Acquisition workspace",
    subheading: "Move a target from thesis through diligence into integration.",
    cta: "Add target",
    ctaTo: "/app/decisions",
    sections: [
      { name: "Acquisition mandate", why: "What the acquisition must accomplish to be worth it.", next: "Define the mandate", to: "/app/decisions" },
      { name: "Target pipeline", why: "Targets under consideration, by stage.", next: "Add a target", to: "/app/decisions" },
      { name: "Initial screens", why: "Fast filters that kill or advance a target.", next: "Screen a target", to: "/app/decisions" },
      { name: "Diligence", why: "Evidence organized by thesis, risk and decision.", next: "Open a diligence brief", to: "/app/evidence" },
      { name: "Investment decisions", why: "The go/no-go moments with their supporting evidence.", next: "Create an investment decision", to: "/app/decisions" },
      { name: "Open conditions", why: "What must be true before close, with owners and dates.", next: "Track a condition", to: "/app/decisions" },
      { name: "Integration planning", why: "The work that turns a deal into value.", next: "Plan integration", to: "/app/decisions" },
    ],
    dealStages: ["Sourced", "Screened", "Initial review", "Diligence", "Investment committee", "Approved", "Closed", "Integration", "Value creation"],
  },
  advisor: {
    title: "Advisor workspace",
    subheading: "Move every client engagement forward — with strict client separation.",
    cta: "Add client workspace",
    ctaTo: "/app/decisions",
    sections: [
      { name: "Client portfolio", why: "Your clients and the state of each engagement.", next: "Add a client", to: "/app/decisions" },
      { name: "Client decision queue", why: "Decisions across clients, never mixed.", next: "Open a client decision", to: "/app/decisions" },
      { name: "Open evidence requests", why: "What you have asked each client to provide.", next: "Request evidence", to: "/app/evidence" },
      { name: "Review calendar", why: "Upcoming client reviews and cadence.", next: "Schedule a review", to: "/app/reviews" },
      { name: "Engagement status", why: "Where each engagement stands.", next: "Review engagements", to: "/app/reviews" },
      { name: "Client workspaces", why: "Isolated, permission-controlled client spaces.", next: "Open a client workspace", to: "/app/decisions" },
    ],
    separation: true,
  },
  integration: {
    title: "Data intake",
    subheading: "No integration required. Start with what you have.",
    cta: "Start guided setup",
    ctaTo: "/app",
    intake: true,
    sections: [
      { name: "Answer a few questions", why: "Begin with the minimum questions for a useful starting point.", next: "Start guided setup", to: "/app" },
      { name: "Use an EXITios template", why: "Start from a structured template for your industry.", next: "Choose a template", to: "/app/evidence" },
      { name: "Upload a file", why: "Bring a report or spreadsheet; EXITios maps and labels it.", next: "Upload a file", to: "/app/evidence" },
      { name: "Connect a supported source", why: "Optional — connect a source when you are ready.", next: "Connect a source", to: "/app/data-sources" },
      { name: "Request guided setup", why: "An EXITios specialist helps frame your first decision.", next: "Request guided setup", to: "/app" },
    ],
  },
  evidence: {
    title: "Evidence",
    subheading: "Every finding carries its source, review state and permissions.",
    cta: "Add evidence",
    ctaTo: "/app/evidence",
    sections: EVIDENCE_CATEGORIES.map((c) => ({
      name: c.name,
      why: `${c.items} item${c.items === 1 ? "" : "s"} · state: ${c.state}.`,
      next: "Review evidence",
      to: "/app/evidence",
    })),
  },
  "data-sources": {
    title: "Data sources",
    subheading: "Connected sources and import status.",
    cta: "Connect a source",
    ctaTo: "/app/data-sources",
    sections: [
      { name: "Connected sources", why: "Sources linked to this workspace.", next: "Connect a source", to: "/app/data-sources" },
      { name: "Imports", why: "Recent imports and their status.", next: "Review imports", to: "/app/data-sources" },
      { name: "Mapping", why: "How source fields map to EXITios definitions.", next: "Review mapping", to: "/app/data-sources" },
    ],
  },
  reports: {
    title: "Reports",
    subheading: "Saved views built from reviewed evidence.",
    cta: "New report",
    ctaTo: "/app/reports",
    sections: [
      { name: "Saved reports", why: "Reports you have saved for this workspace.", next: "Create a report", to: "/app/reports" },
      { name: "Scheduled reports", why: "Reports delivered on a cadence.", next: "Schedule a report", to: "/app/reports" },
    ],
  },
  reviews: {
    title: "Reviews",
    subheading: "The cadence that keeps decisions accountable.",
    cta: "Schedule review",
    ctaTo: "/app/reviews",
    sections: [
      { name: "Upcoming reviews", why: "Reviews scheduled for this workspace.", next: "Schedule a review", to: "/app/reviews" },
      { name: "Review history", why: "Past reviews and what changed.", next: "Review history", to: "/app/reviews" },
    ],
  },
  team: {
    title: "Team and access",
    subheading: "Members, roles and workspace permissions.",
    cta: "Invite member",
    ctaTo: "/app/team",
    sections: [
      { name: "Members", why: "People with access to this workspace.", next: "Invite a member", to: "/app/team" },
      { name: "Roles", why: "What each role can do.", next: "Review roles", to: "/app/team" },
      { name: "Permissions", why: "Workspace and evidence-level access.", next: "Review permissions", to: "/app/team" },
    ],
  },
  billing: {
    title: "Billing",
    subheading: "Plan, usage and invoices.",
    cta: "Manage billing",
    ctaTo: "/app/billing",
    sections: [
      { name: "Current plan", why: "Your subscription and limits.", next: "View plan", to: "/app/billing" },
      { name: "Usage", why: "How much of your plan is in use.", next: "View usage", to: "/app/billing" },
      { name: "Invoices", why: "Past invoices and receipts.", next: "View invoices", to: "/app/billing" },
    ],
  },
  settings: {
    title: "Settings",
    subheading: "Workspace, profile and notification preferences.",
    cta: "Save changes",
    ctaTo: "/app/settings",
    sections: [
      { name: "Profile", why: "Your name, email and role.", next: "Edit profile", to: "/app/settings" },
      { name: "Workspace", why: "Workspace name, type and industry.", next: "Edit workspace", to: "/app/settings" },
      { name: "Notifications", why: "What you are alerted about and how.", next: "Edit notifications", to: "/app/settings" },
    ],
  },
  help: {
    title: "Help",
    subheading: "Guides, principles and support.",
    cta: "Contact support",
    ctaTo: "/app/help",
    sections: [
      { name: "Getting started", why: "How to build your first decision brief.", next: "Read guide", to: "/app/help" },
      { name: "Evidence and review states", why: "What each state means and when to use it.", next: "Read guide", to: "/app/help" },
      { name: "Permissions", why: "How workspace and evidence access work.", next: "Read guide", to: "/app/help" },
      { name: "Contact support", why: "Reach the EXITios team.", next: "Contact support", to: "/app/help" },
    ],
  },
};

export const GUIDED_SETUP_FIELDS = [
  { key: "objective", label: "Business objective", options: ["Grow value", "Prepare to sell", "Evaluate an acquisition", "Advise clients", "Unknown"] },
  { key: "industry", label: "Industry", options: ["Home and field services", "Specialty contracting", "Manufacturing", "B2B managed services", "Healthcare practices", "Veterinary and pet services", "Retail and consumer products", "Add later"] },
  { key: "revenueModel", label: "Revenue model", options: ["Recurring service", "Project-based", "Product sales", "Subscription", "Mixed", "Unknown"] },
  { key: "locations", label: "Locations", options: ["Single location", "Multi-location", "Remote", "Not applicable"] },
  { key: "customerModel", label: "Customer model", options: ["B2B", "B2C", "B2B2C", "Unknown"] },
  { key: "constraint", label: "Primary constraint", options: ["Capacity", "Margin", "Retention", "Acquisition", "Capital", "Unknown"] },
  { key: "availableInfo", label: "Available information", options: ["None", "Spreadsheets", "Reports", "CRM", "Mixed", "Add later"] },
  { key: "outcome", label: "Desired outcome", options: ["A clear next decision", "A readiness plan", "A diligence brief", "A client workspace", "Unknown"] },
];